# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wolverindev/git/libnbtplusplus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wolverindev/git/libnbtplusplus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wolverindev/git/libnbtplusplus/CMakeFiles /home/wolverindev/git/libnbtplusplus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wolverindev/git/libnbtplusplus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nbt++

# Build rule for target.
nbt++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nbt++
.PHONY : nbt++

# fast build rule for target.
nbt++/fast:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/build
.PHONY : nbt++/fast

#=============================================================================
# Target rules for targets named format_test

# Build rule for target.
format_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_test
.PHONY : format_test

# fast build rule for target.
format_test/fast:
	$(MAKE) -f test/CMakeFiles/format_test.dir/build.make test/CMakeFiles/format_test.dir/build
.PHONY : format_test/fast

#=============================================================================
# Target rules for targets named zlibstream_test

# Build rule for target.
zlibstream_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlibstream_test
.PHONY : zlibstream_test

# fast build rule for target.
zlibstream_test/fast:
	$(MAKE) -f test/CMakeFiles/zlibstream_test.dir/build.make test/CMakeFiles/zlibstream_test.dir/build
.PHONY : zlibstream_test/fast

#=============================================================================
# Target rules for targets named endian_str_test

# Build rule for target.
endian_str_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 endian_str_test
.PHONY : endian_str_test

# fast build rule for target.
endian_str_test/fast:
	$(MAKE) -f test/CMakeFiles/endian_str_test.dir/build.make test/CMakeFiles/endian_str_test.dir/build
.PHONY : endian_str_test/fast

#=============================================================================
# Target rules for targets named read_test

# Build rule for target.
read_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read_test
.PHONY : read_test

# fast build rule for target.
read_test/fast:
	$(MAKE) -f test/CMakeFiles/read_test.dir/build.make test/CMakeFiles/read_test.dir/build
.PHONY : read_test/fast

#=============================================================================
# Target rules for targets named nbttest

# Build rule for target.
nbttest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nbttest
.PHONY : nbttest

# fast build rule for target.
nbttest/fast:
	$(MAKE) -f test/CMakeFiles/nbttest.dir/build.make test/CMakeFiles/nbttest.dir/build
.PHONY : nbttest/fast

#=============================================================================
# Target rules for targets named write_test

# Build rule for target.
write_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 write_test
.PHONY : write_test

# fast build rule for target.
write_test/fast:
	$(MAKE) -f test/CMakeFiles/write_test.dir/build.make test/CMakeFiles/write_test.dir/build
.PHONY : write_test/fast

src/endian_str.o: src/endian_str.cpp.o

.PHONY : src/endian_str.o

# target to build an object file
src/endian_str.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/endian_str.cpp.o
.PHONY : src/endian_str.cpp.o

src/endian_str.i: src/endian_str.cpp.i

.PHONY : src/endian_str.i

# target to preprocess a source file
src/endian_str.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/endian_str.cpp.i
.PHONY : src/endian_str.cpp.i

src/endian_str.s: src/endian_str.cpp.s

.PHONY : src/endian_str.s

# target to generate assembly for a file
src/endian_str.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/endian_str.cpp.s
.PHONY : src/endian_str.cpp.s

src/io/izlibstream.o: src/io/izlibstream.cpp.o

.PHONY : src/io/izlibstream.o

# target to build an object file
src/io/izlibstream.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/izlibstream.cpp.o
.PHONY : src/io/izlibstream.cpp.o

src/io/izlibstream.i: src/io/izlibstream.cpp.i

.PHONY : src/io/izlibstream.i

# target to preprocess a source file
src/io/izlibstream.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/izlibstream.cpp.i
.PHONY : src/io/izlibstream.cpp.i

src/io/izlibstream.s: src/io/izlibstream.cpp.s

.PHONY : src/io/izlibstream.s

# target to generate assembly for a file
src/io/izlibstream.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/izlibstream.cpp.s
.PHONY : src/io/izlibstream.cpp.s

src/io/ozlibstream.o: src/io/ozlibstream.cpp.o

.PHONY : src/io/ozlibstream.o

# target to build an object file
src/io/ozlibstream.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/ozlibstream.cpp.o
.PHONY : src/io/ozlibstream.cpp.o

src/io/ozlibstream.i: src/io/ozlibstream.cpp.i

.PHONY : src/io/ozlibstream.i

# target to preprocess a source file
src/io/ozlibstream.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/ozlibstream.cpp.i
.PHONY : src/io/ozlibstream.cpp.i

src/io/ozlibstream.s: src/io/ozlibstream.cpp.s

.PHONY : src/io/ozlibstream.s

# target to generate assembly for a file
src/io/ozlibstream.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/ozlibstream.cpp.s
.PHONY : src/io/ozlibstream.cpp.s

src/io/stream_reader.o: src/io/stream_reader.cpp.o

.PHONY : src/io/stream_reader.o

# target to build an object file
src/io/stream_reader.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/stream_reader.cpp.o
.PHONY : src/io/stream_reader.cpp.o

src/io/stream_reader.i: src/io/stream_reader.cpp.i

.PHONY : src/io/stream_reader.i

# target to preprocess a source file
src/io/stream_reader.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/stream_reader.cpp.i
.PHONY : src/io/stream_reader.cpp.i

src/io/stream_reader.s: src/io/stream_reader.cpp.s

.PHONY : src/io/stream_reader.s

# target to generate assembly for a file
src/io/stream_reader.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/stream_reader.cpp.s
.PHONY : src/io/stream_reader.cpp.s

src/io/stream_writer.o: src/io/stream_writer.cpp.o

.PHONY : src/io/stream_writer.o

# target to build an object file
src/io/stream_writer.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/stream_writer.cpp.o
.PHONY : src/io/stream_writer.cpp.o

src/io/stream_writer.i: src/io/stream_writer.cpp.i

.PHONY : src/io/stream_writer.i

# target to preprocess a source file
src/io/stream_writer.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/stream_writer.cpp.i
.PHONY : src/io/stream_writer.cpp.i

src/io/stream_writer.s: src/io/stream_writer.cpp.s

.PHONY : src/io/stream_writer.s

# target to generate assembly for a file
src/io/stream_writer.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/io/stream_writer.cpp.s
.PHONY : src/io/stream_writer.cpp.s

src/tag.o: src/tag.cpp.o

.PHONY : src/tag.o

# target to build an object file
src/tag.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag.cpp.o
.PHONY : src/tag.cpp.o

src/tag.i: src/tag.cpp.i

.PHONY : src/tag.i

# target to preprocess a source file
src/tag.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag.cpp.i
.PHONY : src/tag.cpp.i

src/tag.s: src/tag.cpp.s

.PHONY : src/tag.s

# target to generate assembly for a file
src/tag.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag.cpp.s
.PHONY : src/tag.cpp.s

src/tag_array.o: src/tag_array.cpp.o

.PHONY : src/tag_array.o

# target to build an object file
src/tag_array.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_array.cpp.o
.PHONY : src/tag_array.cpp.o

src/tag_array.i: src/tag_array.cpp.i

.PHONY : src/tag_array.i

# target to preprocess a source file
src/tag_array.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_array.cpp.i
.PHONY : src/tag_array.cpp.i

src/tag_array.s: src/tag_array.cpp.s

.PHONY : src/tag_array.s

# target to generate assembly for a file
src/tag_array.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_array.cpp.s
.PHONY : src/tag_array.cpp.s

src/tag_compound.o: src/tag_compound.cpp.o

.PHONY : src/tag_compound.o

# target to build an object file
src/tag_compound.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_compound.cpp.o
.PHONY : src/tag_compound.cpp.o

src/tag_compound.i: src/tag_compound.cpp.i

.PHONY : src/tag_compound.i

# target to preprocess a source file
src/tag_compound.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_compound.cpp.i
.PHONY : src/tag_compound.cpp.i

src/tag_compound.s: src/tag_compound.cpp.s

.PHONY : src/tag_compound.s

# target to generate assembly for a file
src/tag_compound.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_compound.cpp.s
.PHONY : src/tag_compound.cpp.s

src/tag_list.o: src/tag_list.cpp.o

.PHONY : src/tag_list.o

# target to build an object file
src/tag_list.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_list.cpp.o
.PHONY : src/tag_list.cpp.o

src/tag_list.i: src/tag_list.cpp.i

.PHONY : src/tag_list.i

# target to preprocess a source file
src/tag_list.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_list.cpp.i
.PHONY : src/tag_list.cpp.i

src/tag_list.s: src/tag_list.cpp.s

.PHONY : src/tag_list.s

# target to generate assembly for a file
src/tag_list.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_list.cpp.s
.PHONY : src/tag_list.cpp.s

src/tag_string.o: src/tag_string.cpp.o

.PHONY : src/tag_string.o

# target to build an object file
src/tag_string.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_string.cpp.o
.PHONY : src/tag_string.cpp.o

src/tag_string.i: src/tag_string.cpp.i

.PHONY : src/tag_string.i

# target to preprocess a source file
src/tag_string.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_string.cpp.i
.PHONY : src/tag_string.cpp.i

src/tag_string.s: src/tag_string.cpp.s

.PHONY : src/tag_string.s

# target to generate assembly for a file
src/tag_string.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/tag_string.cpp.s
.PHONY : src/tag_string.cpp.s

src/text/json_formatter.o: src/text/json_formatter.cpp.o

.PHONY : src/text/json_formatter.o

# target to build an object file
src/text/json_formatter.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/text/json_formatter.cpp.o
.PHONY : src/text/json_formatter.cpp.o

src/text/json_formatter.i: src/text/json_formatter.cpp.i

.PHONY : src/text/json_formatter.i

# target to preprocess a source file
src/text/json_formatter.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/text/json_formatter.cpp.i
.PHONY : src/text/json_formatter.cpp.i

src/text/json_formatter.s: src/text/json_formatter.cpp.s

.PHONY : src/text/json_formatter.s

# target to generate assembly for a file
src/text/json_formatter.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/text/json_formatter.cpp.s
.PHONY : src/text/json_formatter.cpp.s

src/value.o: src/value.cpp.o

.PHONY : src/value.o

# target to build an object file
src/value.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/value.cpp.o
.PHONY : src/value.cpp.o

src/value.i: src/value.cpp.i

.PHONY : src/value.i

# target to preprocess a source file
src/value.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/value.cpp.i
.PHONY : src/value.cpp.i

src/value.s: src/value.cpp.s

.PHONY : src/value.s

# target to generate assembly for a file
src/value.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/value.cpp.s
.PHONY : src/value.cpp.s

src/value_initializer.o: src/value_initializer.cpp.o

.PHONY : src/value_initializer.o

# target to build an object file
src/value_initializer.cpp.o:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/value_initializer.cpp.o
.PHONY : src/value_initializer.cpp.o

src/value_initializer.i: src/value_initializer.cpp.i

.PHONY : src/value_initializer.i

# target to preprocess a source file
src/value_initializer.cpp.i:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/value_initializer.cpp.i
.PHONY : src/value_initializer.cpp.i

src/value_initializer.s: src/value_initializer.cpp.s

.PHONY : src/value_initializer.s

# target to generate assembly for a file
src/value_initializer.cpp.s:
	$(MAKE) -f CMakeFiles/nbt++.dir/build.make CMakeFiles/nbt++.dir/src/value_initializer.cpp.s
.PHONY : src/value_initializer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... nbt++"
	@echo "... format_test"
	@echo "... zlibstream_test"
	@echo "... endian_str_test"
	@echo "... read_test"
	@echo "... nbttest"
	@echo "... write_test"
	@echo "... src/endian_str.o"
	@echo "... src/endian_str.i"
	@echo "... src/endian_str.s"
	@echo "... src/io/izlibstream.o"
	@echo "... src/io/izlibstream.i"
	@echo "... src/io/izlibstream.s"
	@echo "... src/io/ozlibstream.o"
	@echo "... src/io/ozlibstream.i"
	@echo "... src/io/ozlibstream.s"
	@echo "... src/io/stream_reader.o"
	@echo "... src/io/stream_reader.i"
	@echo "... src/io/stream_reader.s"
	@echo "... src/io/stream_writer.o"
	@echo "... src/io/stream_writer.i"
	@echo "... src/io/stream_writer.s"
	@echo "... src/tag.o"
	@echo "... src/tag.i"
	@echo "... src/tag.s"
	@echo "... src/tag_array.o"
	@echo "... src/tag_array.i"
	@echo "... src/tag_array.s"
	@echo "... src/tag_compound.o"
	@echo "... src/tag_compound.i"
	@echo "... src/tag_compound.s"
	@echo "... src/tag_list.o"
	@echo "... src/tag_list.i"
	@echo "... src/tag_list.s"
	@echo "... src/tag_string.o"
	@echo "... src/tag_string.i"
	@echo "... src/tag_string.s"
	@echo "... src/text/json_formatter.o"
	@echo "... src/text/json_formatter.i"
	@echo "... src/text/json_formatter.s"
	@echo "... src/value.o"
	@echo "... src/value.i"
	@echo "... src/value.s"
	@echo "... src/value_initializer.o"
	@echo "... src/value_initializer.i"
	@echo "... src/value_initializer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

